[2023-06-28T12:38:44.021+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: predict_rates.generate_predictions_view manual__2023-06-28T12:38:28.354260+00:00 [queued]>
[2023-06-28T12:38:44.028+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: predict_rates.generate_predictions_view manual__2023-06-28T12:38:28.354260+00:00 [queued]>
[2023-06-28T12:38:44.028+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T12:38:44.028+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-06-28T12:38:44.028+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T12:38:44.040+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): generate_predictions_view> on 2023-06-28 12:38:28.354260+00:00
[2023-06-28T12:38:44.046+0000] {standard_task_runner.py:55} INFO - Started process 1097 to run task
[2023-06-28T12:38:44.049+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'predict_rates', 'generate_predictions_view', 'manual__2023-06-28T12:38:28.354260+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/predict_rates.py', '--cfg-path', '/tmp/tmpadr2czi_']
[2023-06-28T12:38:44.051+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask generate_predictions_view
[2023-06-28T12:38:44.206+0000] {task_command.py:389} INFO - Running <TaskInstance: predict_rates.generate_predictions_view manual__2023-06-28T12:38:28.354260+00:00 [running]> on host 3e2e38946fac
[2023-06-28T12:38:44.271+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=predict_rates
AIRFLOW_CTX_TASK_ID=generate_predictions_view
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T12:38:28.354260+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-28T12:38:28.354260+00:00
[2023-06-28T12:38:44.272+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/predict_rates.py", line 45, in generate_predictions_view
    _generate_predictions_view(prediction_df.from_dict(prediction_df))
AttributeError: 'str' object has no attribute 'from_dict'
[2023-06-28T12:38:44.278+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=predict_rates, task_id=generate_predictions_view, execution_date=20230628T123828, start_date=20230628T123844, end_date=20230628T123844
[2023-06-28T12:38:44.289+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task generate_predictions_view ('str' object has no attribute 'from_dict'; 1097)
[2023-06-28T12:38:44.301+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-06-28T12:38:44.317+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
